general {
    lock_cmd             =
    before_sleep_cmd     =
    after_sleep_cmd      =
    ignore_dbus_inhibit  = false
}

listener {
    timeout    = 60
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
